@inline function LV.broyden_banded_model(::LV.ExaModelsBackend, N = 1000; T = Float64, backend = nothing, prod = false, kwargs...)
    n = Int(N)
    c = EM.ExaCore(T; backend = backend, kwargs...)
    EM.@var(c, x, N; start = fill(3, N))
    EM.@var(c, y, N; start = fill(0, N))
    EM.@con(c, LV.broyden_banded_main_constraint(x, k) for k = 1:N÷2)
    EM.@con(c, LV.broyden_banded_y_constraint_1(x, y))
    EM.@con(c, LV.broyden_banded_y_constraint_2(x, y))
    EM.@con(c, LV.broyden_banded_y_constraint_3(x, y))
    EM.@con(c, LV.broyden_banded_y_constraint_4(x, y))
    EM.@con(c, LV.broyden_banded_y_constraint_5(x, y))
    EM.@con(c, LV.broyden_banded_y_constraint_mid(x, y, i) for i in 6:N-1)
    # EM.@con(c, LV.broyden_banded_y_constraint_last(x, y, n))
    EM.@obj(c, LV.broyden_banded_objective(x, y, i) for i in 1:N)
    return EM.ExaModel(c; prod = prod)
end
